# Generated by Django 2.0.3 on 2018-03-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180327_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
