# Generated by Django 2.0.3 on 2018-03-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180327_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addanimal',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
